{% set name = "ipyvtklink" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e0a9b7ef8302a5d1149108e8117031b1c9b27095e7eb0c4c2172e5fd8c2f33a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Pillow
    - ipywidgets
    - ipycanvas >=0.5.0
    - ipyevents >=0.8.0

test:
  imports:
    - ipyvtklink

about:
  home: https://github.com/Kitware/ipyvtklink/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Minimal ipywidget to interface with any Python vtkRenderWindow
  description: |
    ipyvtklink provides an ipywidget interface for interacting with vtkRenderWindows in a Jupyter notebook. This is most notably used with PyVista.
  doc_url: https://github.com/Kitware/ipyvtklink/blob/master/README.md
  dev_url: https://github.com/Kitware/ipyvtklink

extra:
  recipe-maintainers:
    - banesullivan
    - akaszynski
